# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u2SvceyHWzXAj99pPbTU8buMeSGYZWgI
"""

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split, cross_val_score,\
                                    KFold, cross_validate, StratifiedKFold, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import warnings

warnings.filterwarnings('ignore')

"""
MODEL UTILS
"""

def unreg_logreg(X_train, y_train, X_test, y_test):
  cv_folds = 10
  random_state = 42
  kf = KFold(n_splits=cv_folds, shuffle=True, random_state = random_state)

  pipe = Pipeline([
    ('scaler', StandardScaler()),
     ('logreg', LogisticRegression(penalty=None, random_state=random_state,
                                  max_iter = 3500))])
  scoring = ['accuracy', 'precision', 'recall', 'f1', 'roc_auc']
  lr_cv_scores = cross_validate(
      pipe,
      X_train,
      y_train,
      cv=kf,
      scoring=scoring,
      n_jobs=-1,
      return_train_score=True
  )
  print('Cross-validation scores:')
  print(f"Cross-validation accuracy: {lr_cv_scores['test_accuracy'].mean():.4f}")
  print(f"Cross-validation precision: {lr_cv_scores['test_precision'].mean():.4f}")
  print(f"Cross-validation recall: {lr_cv_scores['test_recall'].mean():.4f}")
  print(f"Cross-validation f1: {lr_cv_scores['test_f1'].mean():.4f}")
  print(f"Cross-validation roc_auc: {lr_cv_scores['test_roc_auc'].mean():.4f}")
  print('------------------------------------------------------------------------')

  pipe.fit(X_train, y_train) #refit model on all training data before proceeding to final model
  lr = pipe.named_steps['logreg']

  unreg_coef_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Coefficient': lr.coef_[0],
    'Odds_Ratio': np.exp(lr.coef_[0])})
  unreg_coef_df = unreg_coef_df.sort_values('Coefficient', ascending=False)

  print("Unregularized Model Coefficients:")
  print(unreg_coef_df)
  print("\nIntercept:", lr.intercept_[0])
  print('------------------------------------------------------------------------')

  y_pred = pipe.predict(X_test)
  y_pred_proba = pipe.predict_proba(X_test)[:, 1]

  test_accuracy = accuracy_score(y_test, y_pred)
  test_precision = precision_score(y_test, y_pred)
  test_recall = recall_score(y_test, y_pred)
  test_f1 = f1_score(y_test, y_pred)
  test_roc_auc = roc_auc_score(y_test, y_pred_proba)

  print('Test scores:')
  print(f"Test Accuracy:  {test_accuracy:.4f}")
  print(f"Test Precision: {test_precision:.4f}")
  print(f"Test Recall:    {test_recall:.4f}")
  print(f"Test F1:        {test_f1:.4f}")
  print(f"Test ROC AUC:   {test_roc_auc:.4f}")

  return pipe, lr_cv_scores, lr, unreg_coef_df, test_accuracy, test_precision, test_recall, test_f1, test_roc_auc

def lasso_logreg(X_train, y_train, X_test, y_test):
  cv_folds = 10
  random_state = 42
  scoring = ['accuracy', 'precision', 'recall', 'f1', 'roc_auc']

  cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=random_state)


  c_grid = np.logspace(-3, 10, 14)
  param_grid = {"logregl1__C": c_grid}

  l1pipe = Pipeline([
      ('scaler', StandardScaler()),
      ('logregl1', LogisticRegression(penalty='l1', solver="liblinear", random_state=random_state,
                                    max_iter = 3500))
  ])

  grid_search = GridSearchCV(l1pipe, param_grid, scoring=scoring, refit='f1', cv=cv)
  grid_search.fit(X_train, y_train)

  print('Cross-validation results:')
  print(f"Best C of l1: {grid_search.best_params_['logregl1__C']}")
  print(f"Best F1 of l1: {grid_search.best_score_:.4f}")
  print(f"Cross-validation Mean F1: {grid_search.cv_results_['mean_test_f1'].mean():.4f}", )
  print(f"Cross-validation Mean Accuracy: {grid_search.cv_results_['mean_test_accuracy'].mean():.4f}", )
  print(f"Cross-validation Mean Precision: {grid_search.cv_results_['mean_test_precision'].mean():.4f}", )
  print(f"Cross-validation Mean Recall: {grid_search.cv_results_['mean_test_recall'].mean():.4f}", )
  print(f"Cross-validation Mean ROC AUC: {grid_search.cv_results_['mean_test_roc_auc'].mean():.4f}", )

  print('------------------------------------------------------------------------')

  l1pipe_best = Pipeline([
      ('scaler', StandardScaler()),
      ('logregl1', LogisticRegression(penalty='l1', C=0.1 ,solver="liblinear", random_state=random_state,
                                    max_iter = 3500))
  ])

  l1pipe_best.fit(X_train, y_train)
  l1 = l1pipe_best.named_steps['logregl1']

  l1reg_coef_df = pd.DataFrame({
      'Feature': X_train.columns,
      'Coefficient': l1.coef_[0],
      'Odds_Ratio': np.exp(l1.coef_[0])
  })
  l1reg_coef_df = l1reg_coef_df.sort_values('Coefficient', ascending=False)

  print("Lasso Regularized Model Coefficients:")
  print(l1reg_coef_df)
  print("\nIntercept:", l1.intercept_[0])

  print('------------------------------------------------------------------------')

  y_pred_l1 = l1pipe_best.predict(X_test)
  y_pred_proba_l1 = l1pipe_best.predict_proba(X_test)[:,1]

  l1_test_accuracy = accuracy_score(y_test, y_pred_l1)
  l1_test_precision = precision_score(y_test, y_pred_l1)
  l1_test_recall = recall_score(y_test, y_pred_l1)
  l1_test_f1 = f1_score(y_test, y_pred_l1)
  l1_test_roc_auc = roc_auc_score(y_test, y_pred_proba_l1)

  lasso_score = [l1_test_accuracy, l1_test_precision, l1_test_recall, l1_test_f1, l1_test_roc_auc]

  print('Test scores:')
  print(f"Test Accuracy:  {l1_test_accuracy:.4f}")
  print(f"Test Precision: {l1_test_precision:.4f}")
  print(f"Test Recall:    {l1_test_recall:.4f}")
  print(f"Test F1:        {l1_test_f1:.4f}")
  print(f"Test ROC AUC:   {l1_test_roc_auc:.4f}")

  return l1pipe_best, grid_search, l1, l1reg_coef_df, lasso_score

def ridge_logreg(X_train, y_train, X_test, y_test):
  cv_folds = 10
  random_state = 42
  scoring = ['accuracy', 'precision', 'recall', 'f1', 'roc_auc']

  cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=random_state)

  c_grid = np.logspace(-3, 10, 14)
  param_grid = {"logregl2__C": c_grid}

  l2pipe = Pipeline([
      ('scaler', StandardScaler()),
      ('logregl2', LogisticRegression(penalty='l2', solver="lbfgs", random_state=random_state,
                                    max_iter = 3500))
  ])

  grid_search = GridSearchCV(l2pipe, param_grid, scoring=scoring, refit='f1', cv=cv)
  grid_search.fit(X_train, y_train)

  print('Cross-validation results:')
  print(f"Best C of l2: {grid_search.best_params_['logregl2__C']}")
  print(f"Best F1 of l2: {grid_search.best_score_:.4f}")
  print(f"Cross-validation Mean F1: {grid_search.cv_results_['mean_test_f1'].mean():.4f}", )
  print(f"Cross-validation Mean Accuracy: {grid_search.cv_results_['mean_test_accuracy'].mean():.4f}", )
  print(f"Cross-validation Mean Precision: {grid_search.cv_results_['mean_test_precision'].mean():.4f}", )
  print(f"Cross-validation Mean Recall: {grid_search.cv_results_['mean_test_recall'].mean():.4f}", )
  print(f"Cross-validation Mean ROC AUC: {grid_search.cv_results_['mean_test_roc_auc'].mean():.4f}", )
  print('------------------------------------------------------------------------')

  l2pipe_best = Pipeline([
      ('scaler', StandardScaler()),
      ('logregl2', LogisticRegression(penalty='l2', C=10, solver="lbfgs", random_state=random_state,
                                    max_iter = 3500))
  ])

  l2pipe_best.fit(X_train, y_train)
  l2 = l2pipe_best.named_steps['logregl2']

  l2reg_coef_df = pd.DataFrame({
      'Feature': X_train.columns,
      'Coefficient': l2.coef_[0],
      'Odds_Ratio': np.exp(l2.coef_[0])
  })
  l2reg_coef_df = l2reg_coef_df.sort_values('Coefficient', ascending=False)

  print("Ridge Regularized Model Coefficients:")
  print(l2reg_coef_df)
  print("\nIntercept:", l2.intercept_[0])
  print('------------------------------------------------------------------------')

  y_pred_l2 = l2pipe_best.predict(X_test)
  y_pred_proba_l2 = l2pipe_best.predict_proba(X_test)[:,1]

  l2_test_accuracy = accuracy_score(y_test, y_pred_l2)
  l2_test_precision = precision_score(y_test, y_pred_l2)
  l2_test_recall = recall_score(y_test, y_pred_l2)
  l2_test_f1 = f1_score(y_test, y_pred_l2)
  l2_test_roc_auc = roc_auc_score(y_test, y_pred_proba_l2)

  ridge_score = [l2_test_accuracy, l2_test_precision, l2_test_recall, l2_test_f1, l2_test_roc_auc]

  print(f"Test Accuracy:  {l2_test_accuracy:.4f}")
  print(f"Test Precision: {l2_test_precision:.4f}")
  print(f"Test Recall:    {l2_test_recall:.4f}")
  print(f"Test F1:        {l2_test_f1:.4f}")
  print(f"Test ROC AUC:   {l2_test_roc_auc:.4f}")

  return l2pipe_best, grid_search, l2, l2reg_coef_df, ridge_score

def polynomial_logreg(X_train, y_train, X_test, y_test):
  cv_folds = 10
  random_state = 42
  max_iter = 1000
  poly_lasso_pipeline = Pipeline([
      ('poly', PolynomialFeatures(degree=3, include_bias=False)),
      ('scaler', StandardScaler()),
      ('lr', LogisticRegression(
          penalty='l1',
          solver='liblinear',
          max_iter=max_iter,
          random_state=random_state
      ))
  ])

  param_grid = {'lr__C': np.logspace(-3, 3, 20)}

  scoring = {
      'accuracy': 'accuracy',
      'precision': 'precision',
      'recall': 'recall',
      'f1': 'f1',
      'roc_auc': 'roc_auc'
  }

  kf = KFold(n_splits=10, shuffle=True, random_state=42)

  best_polyreg_lr = GridSearchCV(
      estimator=poly_lasso_pipeline,
      param_grid=param_grid,
      scoring=scoring,
      cv=kf,
      refit='f1',
      n_jobs=-1,
      return_train_score=False
  )

  best_polyreg_lr.fit(X_train, y_train)

  print('Cross-validation results:')
  print(f"Best C (optimized for F1): {best_polyreg_lr.best_params_['lr__C']:.4f}")
  print("\nBest CV metrics (mean across folds):")
  mean_scores = {
      metric: best_polyreg_lr.cv_results_[f'mean_test_{metric}'][best_polyreg_lr.best_index_]
      for metric in scoring.keys()
  }

  for metric, score in mean_scores.items():
      print(f"{metric}: {score:.4f}")

  feature_names = best_polyreg_lr.best_estimator_.named_steps['poly'].get_feature_names_out(X_train.columns)

  final_lr = best_polyreg_lr.best_estimator_.named_steps['lr']

  coefficients = final_lr.coef_[0]

  coef_df = pd.DataFrame({
      'Feature': feature_names,
      'Coefficient': coefficients,
      'Abs_Coefficient': np.abs(coefficients)
  })

  coef_df = coef_df.sort_values('Abs_Coefficient', ascending=False)

  print('------------------------------------------------------------------------')

  print("\nTop non-zero coefficients:")
  print(coef_df[coef_df['Coefficient'] != 0].head(20).to_string())

  return best_polyreg_lr, best_polyreg_lr, final_lr, coef_df

"""
OUTLIER UTILS
"""

IMPLAUSIBLE_THRESHOLDS = {
    "serum_sodium": {
        "min": 100,
        "max": 190
    },
    "serum_creatinine": {
        "min": 0.2
         #no max; see above
    },
    "platelets": {
        "min": 5000,
        "max": 2_000_000
    },
    "ejection_fraction": {
        "min": 0,
        "max": 90
    },
    "creatinine_phosphokinase": {
        "min": 1,
        "max": 250_000
    }
}

def check_row_implausible(row, thresholds=IMPLAUSIBLE_THRESHOLDS):

    issues = {}

    for lab, bounds in thresholds.items():
        if lab not in row or pd.isna(row[lab]):
            continue

        val = row[lab]

        if "min" in bounds and val < bounds["min"]:
            issues[lab] = f"{val} < {bounds['min']}"

        if "max" in bounds and val > bounds["max"]:
            issues[lab] = f"{val} > {bounds['max']}"

    return issues if issues else None

def split_implausible_rows(df, thresholds=IMPLAUSIBLE_THRESHOLDS):

    df_copy = df.copy()

    implausible_info = []

    # loop through the df
    for idx, row in df_copy.iterrows():
        issues = check_row_implausible(row, thresholds)
        implausible_info.append(issues)

    mask_implausible = pd.Series(
      [i is not None for i in implausible_info],
      index=df_copy.index
      )

    # Split df
    df_removed = df_copy[mask_implausible].copy()
    df_clean   = df_copy[~mask_implausible].copy()

    df_removed["implausible_issues"] = [i for i in implausible_info if i is not None]

    summary = {}
    for issues in df_removed["implausible_issues"]:
        for lab in issues:
            summary[lab] = summary.get(lab, 0) + 1

    return df_clean.reset_index(drop=True), df_removed.reset_index(drop=True), summary

def print_implausible_summary(summary):
  if not summary:
      print("No implausible values found.")
      return

  print("Implausible value summary:")
  for lab, count in summary.items():
      print(f"  {lab}: {count} rows flagged")